baseURL = "https://x4d69636861656c.github.io/"
title = "x4d69636861656c Hacking'"
theme = "hugo-trainsh"
languageCode = "en-us"

[params]
mainSections = ["posts"]
defaultColorScheme = "retro"

# Social links
github = "x4d69636861656c"
x = "@0xCYB3RM0NK3Y"
email = "x4d69636861656c@gmail.com"

[outputs]
home = ["HTML", "RSS", "JSON"]